### ISSUE TITLE
PabloDraw rendes two newlines if the 80th character in the row is non empty

### ISSUE THREAD

**Issue by pcroland** [cwensley/pablodraw#38]
The file viewed in notepad++:
![image](https://i.kek.sh/ynAbqE18uUq.png)
(Also looks like this when I save it in PabloDraw)
Opening the file in PabloDraw:
![image](https://i.kek.sh/HDSOyB5gsZt.png)

**Comment by cwensley** [comment]
Yes, this is because in BBS days, the terminals were 80 characters wide.  When getting to the end of the line it would automatically go to the next even without a carriage return.  There is no easy way around this (without breaking it for all old artwork) other than to just not use the 80th character, or make your canvas wider.

**Comment by cwensley** [comment]
Closing as changing this would break all existing artwork.  Thanks again for reporting the issue but since it is a known limitation of the format, one will have to avoid drawing on the last character of each row.  To draw 80 characters wide and save with newlines for each row, one could set the canvas wider.
