### ISSUE TITLE
gnu/linux build documment

### ISSUE THREAD

**Issue by ftoledo** [cwensley/pablodraw#5]
Thanks for open the sources!
Please, add some docs to build it on gnu/linux!

**Comment by cwensley** [comment]
Currently the only way would be to remove Eto.Wpf dependency (as this requires windows to be built), but otherwise should be compilable by installing latest mono-complete from [here](https://mono-project.com) and running msbuild on `Source/PabloDraw/PabloDraw.csproj`  You could also use MonoDevelop as the IDE.

Once Eto 2.4 is released I'll switch it over to nuget dependencies so it should be fully compilable on any platform.

**Comment by rswindell** [comment]
I was hoping to have look-see and potentially fix the .bin file save issue (truncates last line).
I first tried on Windows (MSVC2017, .NET targetpackage, etc.), but failed to build (I can supply the errors if you care).
So now I'm trying on Linux. I have both mono-complete and gtk-sharp2 installed (on Ubuntu 16.04), but I have no "msbuild" with which to build PabloDraw.csproj and I don't know how to "remove Eto.Wpf dependency".

I'd love to help with this project, but I can't build it, that makes it rather difficult. Pointer welcome,

-Rob

**Comment by cwensley** [comment]
@rswindell, I'm glad you're taking a look!  Yes, more details of what error(s) you're running into would help diagnose (otherwise I can't help!).

To compile on Windows, you will probably need to install gtk-sharp from [here](https://dl.xamarin.com/GTKforWindows/Windows/gtk-sharp-2.12.45.msi). Make sure you set the build configuration to "Win Debug" or "Win Release".

On linux, you'll need the [latest mono (5.x)](http://www.mono-project.com/download/#download-lin) to compile.  Removing the Eto.Wpf dependency means to just remove it from the sln and from PabloDraw.csproj as a reference.

Hope that helps!

**Comment by rswindell** [comment]
Thanks for the quick reply.

On Windows, the VS migration report contains these errors:

  | ..\Libraries\Eto\Source\Eto.Mac\Eto.XamMac2 - net45.csproj: The application which this project type is based on was not found. Please try this link for further information: http://go.microsoft.com/fwlink/?LinkID=299083&projecttype=A3F8F2AB-B479-4A4A-A458-A89E7DC349F1

  | PabloDraw.Mac\PabloDraw.Mac.csproj: The application which this project type is based on was not found. Please try this link for further information: http://go.microsoft.com/fwlink/?LinkID=299083&projecttype=A3F8F2AB-B479-4A4A-A458-A89E7DC349F1

After installing gtk-sharp and setting the build configuration to "Win debug", build errors begin with:

Error	CS0738	'ChangeFont' does not implement interface member 'ICommand.DeliveryMethod'. 'ChangeFont.DeliveryMethod' cannot implement 'ICommand.DeliveryMethod' because it does not have the matching return type of 'NetDeliveryMethod'.	Pablo	C:\src\pablodraw\Source\Pablo\Formats\Character\Actions\ChangeFont.cs	8	Active

The complete report of warnings/errors can be found here:
http://synchro.net/pablodraw_win_build_errors.txt

I did clone the Eto and Lindgren projects into the Libraries directory as well. A complete file listing of the Libraries sub-directory can be found here:
http://synchro.net/pablodraw_win_libraries.txt

Thanks,

-Rob
